language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk8
  - openjdk11

services:
  - docker

before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean test -B
